//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
//   using 3Dmigoto v1.3.16 on Sun Aug 03 15:49:28 2025
//
//
// Buffer Definitions:
//
// cbuffer DrawableBuffer
// {
//
//   float4 FogColor;                   // Offset:    0 Size:    16
//   float4 DebugColor;                 // Offset:   16 Size:    16 [unused]
//   float MaterialOpacity;             // Offset:   32 Size:     4 [unused]
//   float AlphaThreshold;              // Offset:   48 Size:     4 [unused]
//
// }
//
// cbuffer SceneBuffer
// {
//
//   row_major float4x4 View;           // Offset:    0 Size:    64 [unused]
//   row_major float4x4 ScreenMatrix;   // Offset:   64 Size:    64 [unused]
//   float2 DepthExportScale;           // Offset:  128 Size:     8 [unused]
//   float2 FogScaleOffset;             // Offset:  144 Size:     8 [unused]
//   float3 CameraPosition;             // Offset:  160 Size:    12
//   float3 CameraDirection;            // Offset:  176 Size:    12
//   float3 DepthFactors;               // Offset:  192 Size:    12 [unused]
//   float2 ShadowDepthBias;            // Offset:  208 Size:     8 [unused]
//   float4 SubframeViewport;           // Offset:  224 Size:    16 [unused]
//   row_major float3x4 DepthToWorld;   // Offset:  240 Size:    48 [unused]
//   float4 DepthToView;                // Offset:  288 Size:    16 [unused]
//   float4 OneOverDepthToView;         // Offset:  304 Size:    16 [unused]
//   float4 DepthToW;                   // Offset:  320 Size:    16 [unused]
//   float4 ClipPlane;                  // Offset:  336 Size:    16 [unused]
//   float2 ViewportDepthScaleOffset;   // Offset:  352 Size:     8 [unused]
//   float2 ColorDOFDepthScaleOffset;   // Offset:  368 Size:     8 [unused]
//   float2 TimeVector;                 // Offset:  384 Size:     8 [unused]
//   float3 HeightFogParams;            // Offset:  400 Size:    12 [unused]
//   float3 GlobalAmbient;              // Offset:  416 Size:    12 [unused]
//   float4 GlobalParams[16];           // Offset:  432 Size:   256
//   float DX3_SSAOScale;               // Offset:  688 Size:     4
//   float4 ScreenExtents;              // Offset:  704 Size:    16
//   float2 ScreenResolution;           // Offset:  720 Size:     8 [unused]
//   float4 PSSMToMap1Lin;              // Offset:  736 Size:    16
//   float4 PSSMToMap1Const;            // Offset:  752 Size:    16
//   float4 PSSMToMap2Lin;              // Offset:  768 Size:    16
//   float4 PSSMToMap2Const;            // Offset:  784 Size:    16
//   float4 PSSMToMap3Lin;              // Offset:  800 Size:    16
//   float4 PSSMToMap3Const;            // Offset:  816 Size:    16
//   float4 PSSMDistances;              // Offset:  832 Size:    16
//   row_major float4x4 WorldToPSSM0;   // Offset:  848 Size:    64 [unused]
//   float StereoOffset;                // Offset:  412 Size:     4 [unused]
//
// }
//
// cbuffer MaterialBuffer
// {
//
//   float4 MaterialParams[32];         // Offset:    0 Size:   512
//
// }
//
// cbuffer LightBuffer
// {
//
//   struct Light
//   {
//
//       float4 position;               // Offset:    0
//       float3 direction;              // Offset:   16
//       float4 attParams;              // Offset:   32
//       float4 spotParams;             // Offset:   48
//       float4 diffuseColor;           // Offset:   64
//       float4 shadowFadeParams;       // Offset:   80
//
//   } ShadowLights[3];                 // Offset:    0 Size:   288
//
//   struct Light
//   {
//
//       float4 position;               // Offset:  288
//       float3 direction;              // Offset:  304
//       float4 attParams;              // Offset:  320
//       float4 spotParams;             // Offset:  336
//       float4 diffuseColor;           // Offset:  352
//       float4 shadowFadeParams;       // Offset:  368
//
//   } NonShadowLights[3];              // Offset:  288 Size:   288
//
//   struct Light
//   {
//
//       float4 position;               // Offset:  576
//       float3 direction;              // Offset:  592
//       float4 attParams;              // Offset:  608
//       float4 spotParams;             // Offset:  624
//       float4 diffuseColor;           // Offset:  640
//       float4 shadowFadeParams;       // Offset:  656
//
//   } SunLight;                        // Offset:  576 Size:    96
//   row_major float4x4 WorldToShadowMap[3];// Offset:  672 Size:   192
//   row_major float3x4 WorldToModulationMapSpot[2];// Offset:  864 Size:    96
//   row_major float2x4 WorldToModulationMapSun;// Offset:  960 Size:    32
//   bool ShadowLightEnabled[3];        // Offset:  992 Size:    36
//   bool NonShadowLightEnabled[3];     // Offset: 1040 Size:    36
//   bool SunLightEnabled;              // Offset: 1088 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// p_default_Material_057C886416661526_05A108243472522_Texture_sampler    sampler      NA          NA    0        1
// p_default_Normal_050F2CA413890394_05A108244333199_Texture_sampler    sampler      NA          NA    1        1
// p_default_Material_0B0BEA241976566_02F06DA47705948_NormalBufferTexture_sampler    sampler      NA          NA    2        1
// p_default_Material_1D0CD67C7802500_0933A3E46758662_Texture_sampler    sampler      NA          NA    3        1
// p_default_Material_064630A41423171_05D185E43281854_0581B3643227900_DeferredBufferTexture_sampler    sampler      NA          NA    4        1
// p_default_Material_1059CE644560560_103B0A2411213229_Texture_sampler    sampler      NA          NA    5        1
// ShadowBuffer_sampler              sampler      NA          NA   10        1
// GlobalModulationMapSamplers       sampler      NA          NA   11        3
// ShadowMapSampler_sampler        sampler_c      NA          NA   14        1
// AttenuationSampler_sampler        sampler      NA          NA   15        1
// p_default_Material_057C886416661526_05A108243472522_Texture_texture    texture  float4          2d    0        1
// p_default_Normal_050F2CA413890394_05A108244333199_Texture_texture    texture  float4          2d    1        1
// p_default_Material_0B0BEA241976566_02F06DA47705948_NormalBufferTexture_texture    texture  float4          2d    2        1
// p_default_Material_1D0CD67C7802500_0933A3E46758662_Texture_texture    texture  float4        cube    3        1
// p_default_Material_064630A41423171_05D185E43281854_0581B3643227900_DeferredBufferTexture_texture    texture  float4          2d    4        1
// p_default_Material_1059CE644560560_103B0A2411213229_Texture_texture    texture  float4          2d    5        1
// ShadowBuffer_texture              texture  float4          2d   10        1
// GlobalModulationMapTextures       texture  float4          2d   11        3
// ShadowMapSampler_texture          texture  float4          2d   14        1
// AttenuationSampler_texture        texture  float4          2d   15        1
// DrawableBuffer                    cbuffer      NA          NA    1        1
// SceneBuffer                       cbuffer      NA          NA    2        1
// MaterialBuffer                    cbuffer      NA          NA    3        1
// LightBuffer                       cbuffer      NA          NA    4        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyz         2     NONE   float   xyz
// TEXCOORD                 3   xyz         3     NONE   float   xyz
// TEXCOORD                 4   xyz         4     NONE   float   xyz
// TEXCOORD                 5   xyzw        5     NONE   float   xyzw
// TEXCOORD                 6   xyzw        6     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb1[1], immediateIndexed
dcl_constantbuffer cb2[53], immediateIndexed
dcl_constantbuffer cb3[5], immediateIndexed
dcl_constantbuffer cb4[69], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s12, mode_default
dcl_sampler s13, mode_default
dcl_sampler s14, mode_comparison
dcl_sampler s15, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texturecube (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyzw
dcl_output o0.xyzw
dcl_temps 8
add r0.xyz, -v5.xyzx, cb2[10].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.xyzx, r0.wwww
mul r1.xy, v1.xyxx, cb3[2].zwzz
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t1.xywz, s1
mul r1.y, r1.z, r1.y
mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r1.xyxx, r1.xyxx
add r0.w, -r0.w, l(1.000000)
max r0.w, r0.w, l(0.000000)
sqrt r0.w, r0.w
div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb3[3].z
add_sat r2.xy, -|r1.xyxx|, cb3[3].zzzz
mad r1.zw, -r2.xxxy, r1.zzzz, l(0.000000, 0.000000, 1.000000, 1.000000)
mul r1.xy, r1.xyxx, r1.zwzz
mul r1.xy, r1.xyxx, cb3[0].wwww
mul r1.yzw, r1.yyyy, v4.xxyz
mad r1.xyz, r1.xxxx, v3.xyzx, r1.yzwy
mad r1.xyz, r0.wwww, v2.xyzx, r1.xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r1.xyzx, r0.wwww
if_nz cb4[62].x
  ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb4[0].w
  add r2.xyz, -v5.xyzx, cb4[0].xyzx
  dp3 r1.w, r2.xyzx, r2.xyzx
  rsq r1.w, r1.w
  mul r3.xyz, r2.xyzx, r1.wwww
  dp3 r1.w, r3.xyzx, r2.xyzx
  mad r2.xy, r1.wwww, cb4[2].xyxx, cb4[2].zwzz
  dp3 r2.z, r3.xyzx, -cb4[1].xyzx
  mad_sat r2.w, r2.z, cb4[3].x, cb4[3].y
  mul r1.w, r1.w, r2.z
  lt r1.w, r1.w, cb4[3].z
  sample_indexable(texture2d)(float,float,float,float) r2.x, r2.xyxx, t15.zxyw, s15
  mul r2.x, r2.w, r2.x
  mul r4.xyzw, v5.yyyy, cb4[43].xyzw
  mad r4.xyzw, v5.xxxx, cb4[42].xyzw, r4.xyzw
  mad r4.xyzw, v5.zzzz, cb4[44].xyzw, r4.xyzw
  add r4.xyzw, r4.xyzw, cb4[45].xyzw
  add r2.yzw, v5.xxyz, -cb2[10].xxyz
  dp3 r2.y, r2.yzwy, cb2[11].xyzx
  mad_sat r2.zw, r2.yyyy, cb4[5].xxxy, cb4[5].zzzw
  if_nz r0.w
    mad r5.xy, v0.xyxx, cb2[44].zwzz, cb2[44].xyxx
    sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyxx, t10.xyzw, s10
    dp4 r0.w, r5.xyzw, cb4[5].xyzw
  else
    div r4.xy, r4.xyxx, r4.wwww
    add r5.xy, r4.xyxx, l(-0.000122070313, 0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r5.xyxx, t14.xxxx, s14, r4.z
    add r5.xy, r4.xyxx, l(0.000122070313, 0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r5.xyxx, t14.xxxx, s14, r4.z
    add r3.w, r3.w, r4.w
    add r5.xy, r4.xyxx, l(-0.000122070313, -0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r5.xyxx, t14.xxxx, s14, r4.z
    add r3.w, r3.w, r4.w
    add r4.xy, r4.xyxx, l(0.000122070313, -0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r4.x, r4.xyxx, t14.xxxx, s14, r4.z
    add r3.w, r3.w, r4.x
    mul r2.z, r2.z, r3.w
    mad r0.w, r2.z, l(0.250000), r2.w
  endif
  mov r4.xyz, v5.xyzx
  mov r4.w, l(1.000000)
  dp4 r5.x, cb4[54].xyzw, r4.xyzw
  dp4 r5.y, cb4[55].xyzw, r4.xyzw
  sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t12.xyzw, s12
  dp3_sat r2.z, r3.xyzx, r1.xyzx
  mul r3.xyz, r2.zzzz, cb4[4].xyzx
  mul r3.xyz, r5.xyzx, r3.xyzx
  mul r3.xyz, r0.wwww, r3.xyzx
  mul r2.xzw, r2.xxxx, r3.xxyz
  movc r2.xzw, r1.wwww, l(0,0,0,0), r2.xxzw
  if_nz cb4[63].x
    ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb4[6].w
    add r3.xyz, -v5.xyzx, cb4[6].xyzx
    dp3 r1.w, r3.xyzx, r3.xyzx
    rsq r1.w, r1.w
    mul r5.xyz, r3.xyzx, r1.wwww
    dp3 r1.w, r5.xyzx, r3.xyzx
    mad r3.xy, r1.wwww, cb4[8].xyxx, cb4[8].zwzz
    dp3 r3.z, r5.xyzx, -cb4[7].xyzx
    mad_sat r3.w, r3.z, cb4[9].x, cb4[9].y
    mul r1.w, r1.w, r3.z
    lt r1.w, r1.w, cb4[9].z
    sample_indexable(texture2d)(float,float,float,float) r3.x, r3.xyxx, t15.zxyw, s15
    mul r3.x, r3.w, r3.x
    mul r6.xyzw, v5.yyyy, cb4[47].xyzw
    mad r6.xyzw, v5.xxxx, cb4[46].xyzw, r6.xyzw
    mad r6.xyzw, v5.zzzz, cb4[48].xyzw, r6.xyzw
    add r6.xyzw, r6.xyzw, cb4[49].xyzw
    mad_sat r3.yz, r2.yyyy, cb4[11].xxyx, cb4[11].zzwz
    if_nz r0.w
      mad r7.xy, v0.xyxx, cb2[44].zwzz, cb2[44].xyxx
      sample_indexable(texture2d)(float,float,float,float) r7.xyzw, r7.xyxx, t10.xyzw, s10
      dp4 r0.w, r7.xyzw, cb4[11].xyzw
    else
      div r6.xy, r6.xyxx, r6.wwww
      add r7.xy, r6.xyxx, l(-0.000122070313, 0.000162760422, 0.000000, 0.000000)
      sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r7.xyxx, t14.xxxx, s14, r6.z
      add r7.xy, r6.xyxx, l(0.000122070313, 0.000162760422, 0.000000, 0.000000)
      sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.xyxx, t14.xxxx, s14, r6.z
      add r3.w, r3.w, r5.w
      add r7.xy, r6.xyxx, l(-0.000122070313, -0.000162760422, 0.000000, 0.000000)
      sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.xyxx, t14.xxxx, s14, r6.z
      add r3.w, r3.w, r5.w
      add r6.xy, r6.xyxx, l(0.000122070313, -0.000162760422, 0.000000, 0.000000)
      sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r6.xyxx, t14.xxxx, s14, r6.z
      add r3.w, r3.w, r5.w
      mul r3.y, r3.y, r3.w
      mad r0.w, r3.y, l(0.250000), r3.z
    endif
    dp4 r6.x, cb4[57].xyzw, r4.xyzw
    dp4 r6.y, cb4[58].xyzw, r4.xyzw
    sample_indexable(texture2d)(float,float,float,float) r3.yzw, r6.xyxx, t13.wxyz, s13
    dp3_sat r4.x, r5.xyzx, r1.xyzx
    mul r4.xyz, r4.xxxx, cb4[10].xyzx
    mul r3.yzw, r3.yyzw, r4.xxyz
    mul r3.yzw, r0.wwww, r3.yyzw
    mul r3.xyz, r3.xxxx, r3.yzwy
    movc r3.xyz, r1.wwww, l(0,0,0,0), r3.xyzx
    add r2.xzw, r2.xxzw, r3.xxyz
    if_nz cb4[64].x
      ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb4[12].w
      add r3.xyz, -v5.xyzx, cb4[12].xyzx
      dp3 r1.w, r3.xyzx, r3.xyzx
      rsq r1.w, r1.w
      mul r4.xyz, r3.xyzx, r1.wwww
      dp3 r1.w, r4.xyzx, r3.xyzx
      mad r3.xy, r1.wwww, cb4[14].xyxx, cb4[14].zwzz
      dp3 r3.z, r4.xyzx, -cb4[13].xyzx
      mad_sat r3.w, r3.z, cb4[15].x, cb4[15].y
      mul r1.w, r1.w, r3.z
      lt r1.w, r1.w, cb4[15].z
      sample_indexable(texture2d)(float,float,float,float) r3.x, r3.xyxx, t15.zxyw, s15
      mul r3.x, r3.w, r3.x
      mul r5.xyzw, v5.yyyy, cb4[51].xyzw
      mad r5.xyzw, v5.xxxx, cb4[50].xyzw, r5.xyzw
      mad r5.xyzw, v5.zzzz, cb4[52].xyzw, r5.xyzw
      add r5.xyzw, r5.xyzw, cb4[53].xyzw
      mad_sat r3.yz, r2.yyyy, cb4[17].xxyx, cb4[17].zzwz
      if_nz r0.w
        mad r6.xy, v0.xyxx, cb2[44].zwzz, cb2[44].xyxx
        sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r6.xyxx, t10.xyzw, s10
        dp4 r0.w, r6.xyzw, cb4[17].xyzw
      else
        div r5.xy, r5.xyxx, r5.wwww
        add r6.xy, r5.xyxx, l(-0.000122070313, 0.000162760422, 0.000000, 0.000000)
        sample_c_lz_indexable(texture2d)(float,float,float,float) r2.y, r6.xyxx, t14.xxxx, s14, r5.z
        add r6.xy, r5.xyxx, l(0.000122070313, 0.000162760422, 0.000000, 0.000000)
        sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t14.xxxx, s14, r5.z
        add r2.y, r2.y, r3.w
        add r6.xy, r5.xyxx, l(-0.000122070313, -0.000162760422, 0.000000, 0.000000)
        sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t14.xxxx, s14, r5.z
        add r2.y, r2.y, r3.w
        add r5.xy, r5.xyxx, l(0.000122070313, -0.000162760422, 0.000000, 0.000000)
        sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r5.xyxx, t14.xxxx, s14, r5.z
        add r2.y, r2.y, r3.w
        mul r2.y, r3.y, r2.y
        mad r0.w, r2.y, l(0.250000), r3.z
      endif
      dp3_sat r2.y, r4.xyzx, r1.xyzx
      mul r3.yzw, r2.yyyy, cb4[16].xxyz
      mul r3.yzw, r0.wwww, r3.yyzw
      mul r3.xyz, r3.xxxx, r3.yzwy
      movc r3.xyz, r1.wwww, l(0,0,0,0), r3.xyzx
      add r2.xzw, r2.xxzw, r3.xxyz
    endif
  endif
else
  mov r2.xzw, l(0,0,0,0)
endif
if_nz cb4[65].x
  add r3.xyz, -v5.xyzx, cb4[18].xyzx
  dp3 r0.w, r3.xyzx, r3.xyzx
  rsq r0.w, r0.w
  mul r4.xyz, r3.xyzx, r0.wwww
  dp3 r0.w, r4.xyzx, r3.xyzx
  mad r3.xy, r0.wwww, cb4[20].xyxx, cb4[20].zwzz
  dp3 r1.w, r4.xyzx, -cb4[19].xyzx
  mad_sat r2.y, r1.w, cb4[21].x, cb4[21].y
  mul r0.w, r0.w, r1.w
  lt r0.w, r0.w, cb4[21].z
  sample_indexable(texture2d)(float,float,float,float) r1.w, r3.xyxx, t15.xywz, s15
  mul r1.w, r2.y, r1.w
  dp3_sat r2.y, r4.xyzx, r1.xyzx
  mul r3.xyz, r2.yyyy, cb4[22].xyzx
  mul r3.xyz, r1.wwww, r3.xyzx
  movc r3.xyz, r0.wwww, l(0,0,0,0), r3.xyzx
  add r2.xzw, r2.xxzw, r3.xxyz
  if_nz cb4[66].x
    add r3.xyz, -v5.xyzx, cb4[24].xyzx
    dp3 r0.w, r3.xyzx, r3.xyzx
    rsq r0.w, r0.w
    mul r4.xyz, r3.xyzx, r0.wwww
    dp3 r0.w, r4.xyzx, r3.xyzx
    mad r3.xy, r0.wwww, cb4[26].xyxx, cb4[26].zwzz
    dp3 r1.w, r4.xyzx, -cb4[25].xyzx
    mad_sat r2.y, r1.w, cb4[27].x, cb4[27].y
    mul r0.w, r0.w, r1.w
    lt r0.w, r0.w, cb4[27].z
    sample_indexable(texture2d)(float,float,float,float) r1.w, r3.xyxx, t15.xywz, s15
    mul r1.w, r2.y, r1.w
    dp3_sat r2.y, r4.xyzx, r1.xyzx
    mul r3.xyz, r2.yyyy, cb4[28].xyzx
    mul r3.xyz, r1.wwww, r3.xyzx
    movc r3.xyz, r0.wwww, l(0,0,0,0), r3.xyzx
    add r2.xzw, r2.xxzw, r3.xxyz
    if_nz cb4[67].x
      add r3.xyz, -v5.xyzx, cb4[30].xyzx
      dp3 r0.w, r3.xyzx, r3.xyzx
      rsq r0.w, r0.w
      mul r4.xyz, r3.xyzx, r0.wwww
      dp3 r0.w, r4.xyzx, r3.xyzx
      mad r3.xy, r0.wwww, cb4[32].xyxx, cb4[32].zwzz
      dp3 r1.w, r4.xyzx, -cb4[31].xyzx
      mad_sat r2.y, r1.w, cb4[33].x, cb4[33].y
      mul r0.w, r0.w, r1.w
      lt r0.w, r0.w, cb4[33].z
      sample_indexable(texture2d)(float,float,float,float) r1.w, r3.xyxx, t15.xywz, s15
      mul r1.w, r2.y, r1.w
      dp3_sat r2.y, r4.xyzx, r1.xyzx
      mul r3.xyz, r2.yyyy, cb4[34].xyzx
      mul r3.xyz, r1.wwww, r3.xyzx
      movc r3.xyz, r0.wwww, l(0,0,0,0), r3.xyzx
      add r2.xzw, r2.xxzw, r3.xxyz
    endif
  endif
endif
if_nz cb4[68].x
  ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb4[36].w
  lt r3.xyzw, v6.wwww, cb2[52].yzwx
  movc r4.xyz, r3.xxxx, cb2[46].xyzx, l(1.000000,1.000000,1.000000,0)
  and r5.xyz, r3.xxxx, cb2[47].xyzx
  movc r4.xyz, r3.yyyy, cb2[48].xyzx, r4.xyzx
  movc r5.xyz, r3.yyyy, cb2[49].xyzx, r5.xyzx
  movc r4.xyz, r3.zzzz, cb2[50].xyzx, r4.xyzx
  movc r3.xyz, r3.zzzz, cb2[51].xyzx, r5.xyzx
  mad r3.xyz, v6.xyzx, r4.xyzx, r3.xyzx
  if_nz r0.w
    mad r4.xy, v0.xyxx, cb2[44].zwzz, cb2[44].xyxx
    sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t10.xyzw, s10
    dp4 r0.w, r4.xyzw, cb4[41].xyzw
  else
    add r4.xy, r3.xyxx, l(-0.000122070313, 0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r1.w, r4.xyxx, t14.xxxx, s14, r3.z
    add r4.xy, r3.xyxx, l(0.000122070313, 0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r2.y, r4.xyxx, t14.xxxx, s14, r3.z
    add r1.w, r1.w, r2.y
    add r4.xy, r3.xyxx, l(-0.000122070313, -0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r2.y, r4.xyxx, t14.xxxx, s14, r3.z
    add r1.w, r1.w, r2.y
    add r3.xy, r3.xyxx, l(0.000122070313, -0.000162760422, 0.000000, 0.000000)
    sample_c_lz_indexable(texture2d)(float,float,float,float) r2.y, r3.xyxx, t14.xxxx, s14, r3.z
    add r1.w, r1.w, r2.y
    mul r0.w, r1.w, l(0.250000)
  endif
  movc r0.w, r3.w, r0.w, l(1.000000)
  mov r3.xyz, v5.xyzx
  mov r3.w, l(1.000000)
  dp4 r4.x, cb4[60].xyzw, r3.xyzw
  dp4 r4.y, cb4[61].xyzw, r3.xyzw
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r4.xyxx, t11.xyzw, s11
  dp3_sat r1.w, -cb4[37].xyzx, r1.xyzx
  mul r4.xyz, r1.wwww, cb4[40].xyzx
  mul r3.xyz, r3.xyzx, r4.xyzx
  mad r2.xzw, r3.xxyz, r0.wwww, r2.xxzw
endif
dp3 r0.w, r1.xyzx, l(0.250000, 0.250000, 1.000000, 0.000000)
mad r0.w, r0.w, l(0.500000), l(0.500000)
add r3.xyz, cb2[27].xyzx, -cb2[28].xyzx
mad r3.xyz, r0.wwww, r3.xyzx, cb2[28].xyzx
mul r4.xy, v1.wzww, cb3[2].xyxx
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t5.xyzw, s5
mul r5.xy, v1.xyxx, cb3[3].xyxx
sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t0.xyzw, s0
mul r5.xyz, r5.xyzx, cb3[1].xyzx
mad r6.xy, v0.xyxx, cb2[44].zwzz, cb2[44].xyxx
sample_indexable(texture2d)(float,float,float,float) r7.xyz, r6.xyxx, t4.xyzw, s4
mad r2.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r2.xzwx
dp3 r0.w, r0.xyzx, r1.xyzx
add r0.w, r0.w, r0.w
mad r0.xyz, r1.xyzx, -r0.wwww, r0.xyzx
mov r0.xyz, -r0.xyzx
sample_indexable(texturecube)(float,float,float,float) r0.xyz, r0.xyzx, t3.xyzw, s3
mul r0.xyz, r0.xyzx, cb3[4].xxxx
mul r0.xyz, r0.xyzx, cb3[0].xyzx
mul r0.xyz, r4.xyzx, r0.xyzx
mul r0.w, cb2[33].x, cb3[1].w
mad r1.x, cb2[33].x, l(0.400000), l(1.000000)
mul r1.xyz, r2.xyzx, r1.xxxx
mad r2.xyz, -cb2[33].xxxx, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r1.w, -cb2[33].x, cb3[1].w, l(1.000000)
mad r4.xyz, r5.xyzx, r1.wwww, r0.wwww
mad r1.xyz, r3.xyzx, r2.xyzx, r1.xyzx
mul r0.xyz, r0.xyzx, r1.xyzx
// Luma: removed sat (it clipped lighting)
mad r0.xyz, r4.xyzx, r1.xyzx, r0.xyzx
mul r1.xy, r6.xyxx, cb2[43].xxxx
sample_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t2.xyzw, s2
mul r1.xyz, r0.xyzx, r0.wwww
mul r1.w, cb2[33].x, cb3[3].w
// Luma: fixed BT.601 luminance
dp3 r2.x, r0.xyzx, l(0.2126, 0.7152, 0.0722, 0.000000)
mul r2.x, r2.x, r2.x
mul o0.w, r1.w, r2.x
// Luma: remove sat?
mov_sat r1.w, v5.w
mul r1.w, r1.w, cb2[29].x
mad r0.xyz, -r0.xyzx, r0.wwww, cb1[0].xyzx
mad o0.xyz, r1.wwww, r0.xyzx, r1.xyzx
ret
// Approximately 311 instruction slots used
