name: cpp-linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  cpp-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: false
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1